---
# tasks file for jenkins
- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    description: jenkins repository
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    enabled: no
    gpgcheck: yes    

- name: Install Jenkins
  yum:
    name: jenkins
    enablerepo: jenkins
    state: present    

- name: Start Jenkins
  systemd:
    name: jenkins
    enabled: true
    state: started    

- name: Sleep for 30 seconds and continue with play
  wait_for: timeout=30
    
