---
# tasks file for jenkins
- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Download jenkins.repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins-2.138.2-1.1.noarch.rpm
    dest: /etc/yum.repos.d/jenkins.repo   

- name: Install Jenkins
  yum:
    name: jenkins
    enablerepo: jenkins
    state: present    

- name: Start Jenkins
  systemd:
    name: jenkins
    enabled: true
    state: started    

- name: Sleep for 30 seconds and continue with play
  wait_for: timeout=30
    
